def butterfly998244353(a: list[int]) -> list[int]: ...
def butterfly_inv998244353(a: list[int]) -> list[int]: ...
def butterfly(a: list[int], p: int) -> list[int]: ...
def butterfly_inv(a: list[int], p: int) -> list[int]: ...
