def convolution998244353(a: list[int], b: list[int]) -> list[int]: ...
def convolution(a: list[int], b: list[int], p: int) -> list[int]: ...
def convolution_ll(a: list[int], b: list[int]) -> list[int]: ...
