class mf_graph:
    def __init__(self, n: int = 0) -> None: ...
    def add_edge(self, from_: int, to: int, cap: int) -> int: ...
    def flow(self, s: int, t: int, flow_limit: int = 0x7FFF_FFFF_FFFF_FFFF) -> int: ...
    def min_cut(self, s: int) -> list[bool]: ...
    class edge:
        from_: int
        to: int
        cap: int
        flow: int
        def __init__(self, from_: int, to: int, cap: int, flow: int) -> None: ...
        def __repr__(self) -> str: ...
    def get_edge(self, i: int) -> edge: ...
    def edges(self) -> list[edge]: ...
    def change_edge(self, i: int, new_cap: int, new_flow: int) -> None: ...
