from typing import overload
@overload
def suffix_array(s: str) -> list[int]: ...
@overload
def suffix_array(s: list[int]) -> list[int]: ...
@overload
def suffix_array(s: list[int], upper: int) -> list[int]: ...
def lcp_array(s: str | list[int], sa: list[int]) -> list[int]: ...
def z_algorithm(s: str | list[int]) -> list[int]: ...
