class two_sat:
    def __init__(self, n: int = 0) -> None: ...
    def add_clause(self, i: int, f: bool, j: int, g: bool) -> None: ...
    def satisfiable(self) -> bool: ...
    def answer(self) -> list[bool]: ...
