name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure the full history is fetched

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' 

    - name: Install dependencies
      run: |
        python -m pip install Sphinx sphinx-copybutton sphinx-rtd-theme sphinx-intl myst-parser

    - name: Update .po files
      run: |
        make -C docs update-po

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[skip actions] Update .po files"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"

    - name: Build Sphinx documentation
      run: |
        make -C docs ja en

    - name: Deploy to GitHub Pages (ja)
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/ja/html
        publish_branch: gh-pages
        destination_dir: ${{ github.ref_name == 'main' && 'ja' || 'develop/ja' }}

    - name: Deploy to GitHub Pages (en)
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/en/html
        publish_branch: gh-pages
        destination_dir: ${{ github.ref_name == 'main' && 'en' || 'develop/en' }}
