name: Publish to PyPI

on:
  push:
    tags: ["*"]

jobs:
  publish_package:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' 

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo 'docs/\ntests/\n.github/\n.gitignore' >> .gitignore
          python -m pip install twine build
          python -m build --sdist
          twine upload dist/*
